### ISSUE TITLE
slack fetch user

### ISSUE THREAD

**Issue by bryanl** [markbates/goth#100]
The way this is currently implemented leaves a bit to be desired. If using goth for a slack app bot, you won't be able fetch the pertinent bot details e.g bot id, bot channel id, bot oauth2 token. I hesitate to submit a PR for this (but probably will anyways), because I don't know how others are dealing with this brokenness. In its current state, it's not very useful for a bot application.

**Comment by markbates** [comment]
I'm open for suggestions on how to fix/change things for a potential v2.

**Comment by bryanl** [comment]
I don't think you need do a rev on goth to make this work. This is more commentary about how the slack provider works. It looks to be a simple copy and paste of the box provider without considering how it would actually be used. I'm tweaking a local copy now to see what changes need to be made.

**Comment by bryanl** [comment]
More thoughts on this.  IF there was a v2, I would like the ability to have more than one instance of a provider. If you are dealing with a single provider with multiple scopes (because you have multiple users), things can get a bit hairy with the default setup.  It's possible to maintain your own list of providers, so this is something that can be worked around.

**Comment by willemvd** [comment]
With #130 it is now possible to set a name to the provider which makes it possible to have multiple instances of the same provider

**Comment by willemvd** [comment]
@bryanl can you confirm if the bot data can be retrieved from the endpointProfile https://slack.com/api/users.info ? 

Because if so, it should be available inside gothUser.RawData :  https://github.com/markbates/goth/blob/master/providers/slack/slack.go#L116 
With that RawData you can than afterwards parse out your requested data

If it is not available, please let me know

**Comment by bentranter** [comment]
Closing this due to age, feel free to re-open if it's still an issue.
