### ISSUE TITLE
request for wechat provider support

### ISSUE THREAD

**Issue by tvmaly** [markbates/goth#101]
would it be possible to add support for wechat as a provider?

http://admin.wechat.com/wiki/index.php?title=User_Profile_via_Web

**Comment by markbates** [comment]
Please feel free and open a PR with WeChat support. It would be welcome. Thanks.

**Comment by thomasmodeneis** [comment]
anyone having any ideas how to integrate wechat ?

**Comment by rushairer** [comment]
https://github.com/markbates/goth/pull/486
