### ISSUE TITLE
Using goth for rest api

### ISSUE THREAD

**Issue by Guiguillermo** [markbates/goth#104]
Hello,

I want to implement Facebook social login on a mobile app.
It looks like goth is designed for web app, not mobile app (for example, the http redirection is not possible).
Is there a way to use the power of goth to create a rest service for facebook login ? 

Thanks in advance.

**Comment by markbates** [comment]
Great question. I don't know. The `gothic` package is explicitly designed for web apps, however, it just wraps most of `goth` to make that happen. You can probably use the individual pieces to make it happen, but I've never done it, so I can't really say for sure.
