### ISSUE TITLE
Use new Client() in all cases

### ISSUE THREAD

**Issue by willemvd** [markbates/goth#123]
Seems that not all http.Get (and maybe .Post?) are replaced with the new Client() from the provider.
Example: https://github.com/markbates/goth/blob/master/providers/github/github.go#L154

**Comment by markbates** [comment]
I replaced all the ones that had been set up by that last PR Felix set up, so that must've missed a bunch of places. 

PR? Please?

**Comment by willemvd** [comment]
Ok, will try to do that tomorrow but not sure if I will get to it :)
