### ISSUE TITLE
Username/Password Authentication?

### ISSUE THREAD

**Issue by tylerstillwater** [markbates/goth#14]
Would Username/Password authentication be something we want in goth?

**Comment by digitalplaywright** [comment]
https://github.com/simplabs/rails_api_auth is a rails example for supporting the "Resource Owner Password Credentials Grant" OAuth 2.0 flow as well as Facebook authentication. It is extremely simple and not many lines of code, and hopefully this can be made into an equivalent. However, the scope of this package is for APIs with bearer tokens only and not for cookie based sessions.

**Comment by lucagez** [comment]
This PR https://github.com/markbates/goth/pull/506 can add support for the Password Grant flow
