### ISSUE TITLE
Add support for dynamic client registration

### ISSUE THREAD

**Issue by strk** [markbates/goth#142]
I'm looking for `OpenID-2.0` style of authentication: just present an URL you control and you're in!
In order to do that, we must remove the need to hard-code clientID/clientSecret in relaying parties configurations, and dynamic client registration seems to be what's needed for that:
https://openid.net/specs/openid-connect-registration-1_0.html

Is that supported by the openid provider, or does it need to be supported by core directly  ?

\cc @willemvd

**Comment by willemvd** [comment]
Guess you mean OpenID Connect instead of OpenID? 
In case of OpenID Connect, I think that you need to modify the OpenID Connect provider since the core is not aware of the implementation of the provider.
Creating a new provider is also possible as long as you implement the Provider and Session interface, which both doesn't need to do OAuth2 specific things

**Comment by strk** [comment]
Yes I meant `OpenID Connect provider`. So you confirm it's not supported but could be made supported by the provider w/out changes in Core, did I understand correctly ?

The "no need to do OAuth2 specific things" part isn't clear to me, does it mean a provider could *also* just be plain `OpenID-2.0`, for example ?

**Comment by willemvd** [comment]
> So you confirm it's not supported but could be made supported by the provider w/out changes in Core, did I understand correctly ?

Yes, I do confirm it can be supported by provider without changes to the core.

> The "no need to do OAuth2 specific things" part isn't clear to me, does it mean a provider could also just be plain OpenID-2.0, for example ?

Yes that is what I mean 😄

**Comment by strk** [comment]
I found a wider specification to actually allow what I'm after (federated logins). #148 filed to superceed this.
