### ISSUE TITLE
Are examples broken?

### ISSUE THREAD

**Issue by thalesfsp** [markbates/goth#153]
I followed the instruction to run the example, and tried some. Some are broken, I think:

- Slack
- SoundCloud
- etc

Can you confirm it? Am I doing something wrong or missing some step?

Thank you!

**Comment by xenu256** [comment]
Facebook too gives:
"The parameter app_id is required", when config is intact.

**Comment by xenu256** [comment]
OK, got it. This isn't an issue, but documentation should be clearer, probably. The ids and secrets should be set through environment variables, ex.:

```go
os.Setenv("FACEBOOK_KEY", "2154664641")
os.Setenv("FACEBOOK_SECRET", "5654646464646868")
```
