### ISSUE TITLE
[Question] Oauth 1.0a

### ISSUE THREAD

**Issue by apaganobeleno** [markbates/goth#156]
First of all thanks for all the providers goth has! 
I would like to know if by chance there is a sample of oauth 1.0a provider somewhere, and also if goth supports oauth 1.0a.

Thanks in advance!

**Comment by markbates** [comment]
Hey @apaganobeleno, each provider uses what ever implementation of OAuth the service it talks to uses. For example, Twitter is OAuth 1.0a and GitHub is OAuth 2. It's even possible to implement a provider that doesn't use OAuth at all! :) Hope that answers the question.

**Comment by apaganobeleno** [comment]
thanks @markbates for the quick answer, yes, it answers all my questions.
