### ISSUE TITLE
Stronger default cookie security settings for gothic.Store

### ISSUE THREAD

**Issue by ncantelmo** [markbates/goth#160]
By default, gothic's CookieStore is created without additional configuration beyond what's set by `sessions.NewCookieStore([]byte(key))`.

That causes gothic to produce cookies with options:
```go
&Options{
   Path:   "/",
   Domain: "",
   MaxAge: 86400 * 30,
   Secure: false,
   HttpOnly: false,
 }
```

The biggest issue here is the `HttpOnly` flag being false. Enabling that by default would be easy, shouldn't break anything, and would help prevent a large class of XSS attacks.

The other item that's worth noting is the `Secure` flag, which requires cookies to be sent over https. Most modern sites served over TLS will want that flag set in production.

Both of these flags can be enabled using gothic currently, if `gothic.Store` is overridden:

```go
isProd := false
store := sessions.NewCookieStore(key)
store.MaxAge(86400 * 30)  // 30 days
store.Options.Path = "/"
store.Options.HttpOnly = true
if isProd {
  store.Options.Secure = true
}
gothic.Store = store
```

Because this can be configured, I don't think any API changes need to be made to gothic. At the same time, since a lot of gothic users will stick with the defaults, I believe the `HttpOnly` flag should be set by default. It would probably also be a good idea to update the example/README to show how to configure the other options, in particular the `Secure` flag.

**Comment by markbates** [comment]
Sounds good. Can you do a PR for the `HttpOnly` flag and an update to the README?

**Comment by ace03uec** [comment]
This has been merged. This issue should be closed.
