### ISSUE TITLE
Support Xboxlive oauth

### ISSUE THREAD

**Issue by bfosberry** [markbates/goth#163]
https://msdn.microsoft.com/en-us/library/hh243647.aspx

**Comment by michalpristas** [comment]
this flow should be handled by onedrive package, (i did not test it, but auth URIs are the same)

**Comment by bfosberry** [comment]
OOhh thanks I'll look into that

**Comment by bentranter** [comment]
Closing this due to age, feel free to re-open if it's still an issue. Pretty sure this is done with the OneDrive package though, as mentioned.
