### ISSUE TITLE
BUG: got a overflows init variable when session stored

### ISSUE THREAD

**Issue by mckaygerhard** [markbates/goth#178]
i got that error in 
https://github.com/markbates/goth/blob/6c3a31e5f6aa001e8c3d6cec3f65d5bcc0240e69/examples/main.go#L59 , when compiling on 32bit and arm 64bit  filesystems got:

src/github.com/markbates/goth/examples/main.go:65: constant 9223372036854775807 overflows int

when the sesion id cookie stored into the variable

**Comment by bentranter** [comment]
Closing this due to age. I actually think this was a bug with gorilla/sessions that was resolved earlier this year. I'll re-open if anyone else runs into this.
