### ISSUE TITLE
Why logout after completing user auth?

### ISSUE THREAD

**Issue by terev** [markbates/goth#181]
This line was breaking authentication for me when utilizing any store. What is the purpose of this line?

https://github.com/markbates/goth/blob/6c3a31e5f6aa001e8c3d6cec3f65d5bcc0240e69/gothic/gothic.go#L150

**Comment by markbates** [comment]
It clears out the session cookie. If you don’t, you could end up with all sorts of issues when using multiple problems.

-----------
Mark Bates

**Comment by terev** [comment]
Thanks for the reply!
I'm using Gin as my router. Can you see any issues that would arise using the single Gin context vs another router?

When compiling with that line left in, no sessions are being stored with any of the stores I've tried (redis, or cookie). As a result on auth callback I'm receiving the message `could not find a matching session for this request`.

**Comment by markbates** [comment]
I don’t, sorry. That line is a defer, so it happens after everything else has run, and it’s not returning the error, so I’m curious to see what is. Make sure that the host of the page you are on matches the callback host you configured. Often, most OAuth errors are because of mismatched hosts.

**Comment by terev** [comment]
```
r.GET("/auth/:provider/callback", func(context *gin.Context) {
		user, err := gothic.CompleteUserAuth(context.Writer, context.Request)
		if err != nil {
			fmt.Fprintln(context.Writer, err)
			return
		}

		context.JSON(200, user)
	})
```
Is my callback route. So I'm pretty sure its this in CompleteUserAuth: 
```
value, err := getFromSession(providerName, req)
	if err != nil {
		return goth.User{}, err
	}
```
After that returns that call to Logout would execute.

**Comment by markbates** [comment]
I’ve seen similar problems if you try to access the session after that call. You don’t want to do that.

-----------
Mark Bates

**Comment by terev** [comment]
It seems my session isn't even stored in the gorilla session registry when hitting my `/auth/spotify` route. `gothic.BeginAuthHandler(context.Writer, context.Request)` should register a new session in the store right?

**Comment by markbates** [comment]
it should. it just wraps the gorilla sessions package, which is supposed to create a new session if one doesn't exist. maybe the cookies aren't be written? I don't know gin enough to say if there's something there or not.

**Comment by terev** [comment]
The redis session store save method looks like this. Since Logout is called the session's max age is set to -1. As a result the cookie is never written. Not sure what's up with the base cookie session store though.
```
func (s *RediStore) Save(r *http.Request, w http.ResponseWriter, session *sessions.Session) error {
	// Marked for deletion.
	if session.Options.MaxAge < 0 {
		if err := s.delete(session); err != nil {
			return err
		}
		http.SetCookie(w, sessions.NewCookie(session.Name(), "", session.Options))
	} else {
		// Build an alphanumeric key for the redis store.
		if session.ID == "" {
			session.ID = strings.TrimRight(base32.StdEncoding.EncodeToString(securecookie.GenerateRandomKey(32)), "=")
		}
		if err := s.save(session); err != nil {
			return err
		}
		encoded, err := securecookie.EncodeMulti(session.Name(), session.ID, s.Codecs...)
		if err != nil {
			return err
		}
		http.SetCookie(w, sessions.NewCookie(session.Name(), encoded, session.Options))
	}
	return nil
}
```

**Comment by terev** [comment]
I propose the following as a solution:
```
var CompleteUserAuth = func(res http.ResponseWriter, req *http.Request) (goth.User, error) {
	if !keySet && defaultStore == Store {
		fmt.Println("goth/gothic: no SESSION_SECRET environment variable is set. The default cookie store is not available and any calls will fail. Ignore this warning if you are using a different store.")
	}

	providerName, err := GetProviderName(req)
	if err != nil {
		return goth.User{}, err
	}

	provider, err := goth.GetProvider(providerName)
	if err != nil {
		return goth.User{}, err
	}

	value, err := getFromSession(providerName, req)
	if err != nil {
		return goth.User{}, err
	}

	defer Logout(res, req)

	sess, err := provider.UnmarshalSession(value)
	if err != nil {
		return goth.User{}, err
	}

	err = validateState(req, sess)
	if err != nil {
		return goth.User{}, err
	}

	user, err := provider.FetchUser(sess)
	if err == nil {
		// user can be found with existing session data
		return user, err
	}

	// get new token and retry fetch
	_, err = sess.Authorize(provider, req.URL.Query())
	if err != nil {
		return goth.User{}, err
	}

	err = storeInSession(providerName, sess.Marshal(), req, res)

	if err != nil {
		return goth.User{}, err
	}

	gu, err := provider.FetchUser(sess)
	return gu, err
}
```
Basically if there is no session to logout from then don't push the defer. I was wondering though is this not meant to be a long term session handler? Do we really need to remove the session from the store? Why not just delete the state cookie?

**Comment by terev** [comment]
#182

**Comment by kswope** [comment]
This is somehow related to the example

```
	p.Get("/auth/{provider}", func(res http.ResponseWriter, req *http.Request) {
		// try to get the user without re-authenticating
		if gothUser, err := gothic.CompleteUserAuth(res, req); err == nil {
			t, _ := template.New("foo").Parse(userTemplate)
			t.Execute(res, gothUser)
		} else {
			gothic.BeginAuthHandler(res, req)
		}
	})
```

I'm not sure I understand this example in goth/examples/main.go but notice above the call to CompleteUserAuth.  When you call CompleteUserAuth before BeginAuthHandler and keep the defer Logout, the session is broken and you get the error "could not find a matching session for this request".  If you comment the defer, all is well.  If you want to keep the defer Logout, you can't call CompleteUserAuth before BeginAuthHandler.

There is some nasty state stuff going on here.  Maybe when you wipe a session it like Logout does, you can't get it back in proper working order.

**Comment by SuperSarkar** [comment]
How do I retain a logged-in session? I should maintain another session for that?

**Comment by dolanor** [comment]
I have the same question as @SuperSarkar.
I thought I could use `_gothic_session` to handle authentication+authorization.
So if I got it right, the `gothic.CompleteUserAuth()` is just to get every information about the user from the provider, so that we can save what we want/need in our own session/cookies.
That `_gothic_session` is just to handle a state long enough to do the auth to the provider + callback. So then, we don't want that cookie around, since we should have passed those user data to another cookie/session. Is that right?

**Comment by bentranter** [comment]
Hey @dolanor, yes, that's right. `_gothic_session` only exists to handle the OAuth2 state parameter handling, and should not be used for more than that. You should use your own cookie/session for user auth.

**Comment by andig** [comment]
> Hey @dolanor, yes, that's right. `_gothic_session` only exists to handle the OAuth2 state parameter handling, and should not be used for more than that. You should use your own cookie/session for user auth.

I just happened to stumble across the same "problem". It would be great to have an e2e example including logged-in state and logout.

**Comment by Nirn90** [comment]
I wonder, what's the purpose of this line of code if the session is discarded anyway?
https://github.com/markbates/goth/blob/8333bec01e14cc21c0c1ea74e6ed42130db2500d/gothic/gothic.go#L143
