### ISSUE TITLE
Discord implementation does not work.

### ISSUE THREAD

**Issue by fodawim** [markbates/goth#183]
After implementing Discord auth you will receive the following error.

> oauth2: cannot fetch token: 401 Unauthorized
> Response: - {"error": "invalid_client"}

**Comment by bentranter** [comment]
Tested this with my own credentials, and it seems to work fine.

I did some digging and for Discord, if the error that says `invalid_client`, the most common issue is that the `DISCORD_SECRET` is incorrect.

I'm going to close this for now, but feel free to reopen if there are still issues.

**Comment by loockeeer** [comment]
Hello ! I'm getting the same error as fodawim.
```js
        const token = await axios.post(TOKEN_URI,
            null, {headers: {"Content-Type": "application/x-www-form-urlencoded"}, params:{
                client_id: CLIENT_ID,
                client_secret: CLIENT_SECRET,
                grant_type: "authorization_code",
                code: req.query.code,
                redirect_uri: REDIRECT_URI,
                scope: "identify guilds.join"
            }}).catch(console.error)
``` 
I have this code and I'm getting `{ error: 'invalid_client' }`

I don't know why, and if someone can help me to fix this bug, I would be very grateful to him for that.

Thank you in advance, Looockeeer.

**Comment by bentranter** [comment]
I just ran this manually on master, seems like our Discord implementation is still okay.

@loockeeer, it doesn't look like you're using Goth, so I don't think there's much I can do to help you. That said, there are two things I'd review to try to track down the source of your error:

1. If the error occurs at the step where the user is redirected to the auth code URL, you've probably got an invalid client secret. If you can make it past there, your credentials are fine.
2. Make sure that the body of the POST request is in fact encoding the body as `application/x-www-form-urlencoded`, and not something like `application/json` by mistake.

Hope that helps!
