### ISSUE TITLE
It was doing good in localhost, but not working after deploying

### ISSUE THREAD

**Issue by amankapoor** [markbates/goth#185]
I configured the system and it worked great on localhost, I had my client id and secret saved and my callback was http://localhost/auth/gplus/callback.

After publishing my code online, I was not able to login and realised that I did not change the callback url to http://mysitename.com/auth/gplus/callback. I made the change and also entered this new fallback url in the gothic or goth.New() function ( I don't remember that clearly, but I made the change.).

But whenever I try logging in, I get a redirect uri mismatch as google sends localhost link in the callback
```
Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:8080/auth/gplus/callback, does not match the ones authorized for the OAuth client..... 
```
Am I missing any thing?

**Comment by amankapoor** [comment]
I would also like to add that I also tried by creating a new project and using its client secret and id, but even that did not work.

**Comment by markbates** [comment]
OAuth requires that all hosts be exactly the same. That means that the you need to make sure that the app you configured with Google has the same host as the callback URL you give Goth, which has to be the exact same host that you are making the request from. Check ALL three places to make sure they are configured correctly. If one of them is wrong, none of it will work.

**Comment by amankapoor** [comment]
Suppose my site's name is example.com,
So,
1. it looks like this in the app.
```
 goth.UseProviders(
                gplus.New(os.Getenv("OAUTH_CLIENT_ID"), os.Getenv("OAUTH_CLIENT_SECRET"), "http://example.com/auth/gplus/callback"),
        )
```
2. Authorised Redirect URI is set to `http://example.com/auth/gplus/callback`

3. And I am making request from example.com only, and as soon as it visits example.com/auth/gplus, it redirects to 
```
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=1030362162437-qjd6mi9ld2gd0v2kiml6orvd590vpfjm.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauth%2Fgplus%2Fcallback&response_type=code&scope=profile+email+openid&state=ToUiFj6j2fSdsaovCc7VqcstdD4hHwC0HImbL5jrcxlqc0eOTVMewhZdk6u1EptkSmSkb5SIOjejsZ6wWtkxbQ%3D%3D
```
Do I need to enter my domain name anywhere else in developers console?

**Comment by markbates** [comment]
I don't know enough about that platform to give you exact instructions, sorry.

**Comment by amankapoor** [comment]
hmm, okay mark. I will try more.
