### ISSUE TITLE
Check whether a user is authenticated or not

### ISSUE THREAD

**Issue by rcholic** [markbates/goth#186]
First of all, I'm new to `goth` but I think it is the perfect library I would like to use for adding third-party auth to my app. This is more of a question than an issue:

To restrict APIs to only authenticated users, I was wondering if there's an API to check whether the user has been authenticated. If not, I think we can check wether a session exists in the store, i.e. 
```
session, err := Store.Get(req, providerName+SessionName)
	if err != nil || session == nil {
		return err // user not authenticated?
	}

```

**Comment by markbates** [comment]
Goth handles authentication with 3rd party providers. It’s up to you to store that information in a way that makes sense to your app. That usually means saving a user record in your database and usually storing some sort of user if in your session. Goth doesn’t do any of that. The session store goth uses is for its own use during the oauth flow. It’s not for applications to use.
