### ISSUE TITLE
on windows error Error: fork/exec go\bin\buffalo-goth.exe: The parameter is incorrect.

### ISSUE THREAD

**Issue by AucT** [markbates/goth#188]
when i run from windows 10
buffalo generate goth facebook
i get error
Error: fork/exec go\bin\buffalo-goth.exe: The parameter is incorrect.

**Comment by markbates** [comment]
This issue belongs in the https://github.com/gobuffalo/buffalo-goth repository, since it's a problem with the plugin, not Goth itself.
