### ISSUE TITLE
Example code not working: gorilla/sessions attempts to delete newly created session.

### ISSUE THREAD

**Issue by Omustardo** [markbates/goth#192]
I'm attempting to get a basic example of google oauth working. As a base case, I tried running the example code provided in goth/examples but upon clicking the "Log in with Google Plus" button it responded with a text based web page saying:
"remove C:\Users\Omar\AppData\Local\Temp\session_: The system cannot find the file specified."

That error comes from a line in gorilla/sessions where the [FilesystemStore.erase](https://github.com/gorilla/sessions/blob/master/store.go#L287) fails to find a file, so my best guess was that there must have been an error saving the session.

I reported this to [gorilla/sessions](https://github.com/gorilla/sessions/issues/137) and they suggested that the package is being misused to get to this state.

I read more about oauth since I'm new to it, and realized I would need to set up a real domain name in order to avoid having to deal with redirect mismatches #94 so I modified the provided demo to:
1. only use gplus as a provider
2. use my own server cert/key for TLS
3. use my own callback url
My code is here: https://gist.github.com/Omustardo/09ae0eb5a3edf3d0d2520d14143d8c46

I've finally had some time to dig into it, and I found out what's happening. 
Looking at the code, the point of failure is on [FilesystemStore.Save](https://github.com/gorilla/sessions/blob/master/store.go#L216) when a session is provided that has Options.MaxAge==-1

The question is, how does it get a session with MaxAge==-1
The session that's causing the error is retrieved by [Store.Get(req, SessionName)](https://github.com/markbates/goth/blob/master/gothic/gothic.go#L284)

Using a debugger, I traced the path of Store.Get and found that the registry it retrieves from contains multiple SessionInfo entries, keyed by session name. In this case, the provided `SessionName` is a constant = "_gothic_session". As far as I can tell, the MaxAge for this session is always -1, so when we then try to save the session, it immediately attempts to erase the local file (at `os.TempDir() + sessions_`) which doesn't yet exist, and so it returns an error.

I suspect I'm missing some key point, since clearly this example has worked for other people (I hope), but it looks to me like the wrong session is being retrieved from `Store.Get`. Looking at the registry, it contains an entry for "_gothic_session" as well as one for "gplus_gothic_session". The gplus one has MaxAge=2592000 which is what we want.

By modifying storeInSession and getFromSession to call `Store.Get(req, key + SessionName)` instead of `Store.Get(req, SessionName)` I was able to get the modified example code to work. I suspect there might be other places in the code where the providerName should be appended to the SessionName but haven't looked deeply yet.

Am I doing something wrong, or should I submit a pull request to fix this?

**Comment by bentranter** [comment]
Another relevant (but closed) PR, for anyone else who might stumble upon this issue: https://github.com/markbates/goth/pull/199

**Comment by sloba88** [comment]
After loosing a whole day on this issue I figured out what's wrong. First time that you get logged out (if the user is not in the session) global cookie setting is changed to -1 so you can't create a new cookies after this anymore.
https://github.com/markbates/goth/blob/f3fc9dc67dce1e3461e99247d756cccf09e9835d/gothic/gothic.go#L232

**Comment by Perfeto** [comment]
Hi! I don't think this behavior is predictable. For example, when using sessions.NewFilesystemStore or Redis store, I have no problems with using gothic.StoreInSession().

I believe we need to address this issue. 🤔
