### ISSUE TITLE
Example code failure: could not find a matching session for this request

### ISSUE THREAD

**Issue by lsiv568** [markbates/goth#195]
When running the example code with the linkedin provider (or any provider) I get the error `could not find a matching session for this request`.  After doing a bit of debugging I found that the only way the example works is if I remove the [defer in CompletUserAuth handler](https://github.com/markbates/goth/blob/master/gothic/gothic.go#L150).  

I could completely be missing something but it appears as though every time we successfully auth and add the data to the session we are logging out and removing is.  Is this intended behavior?  What am I missing?

Any help you can provide would be greatly appreciated.

**Comment by markbates** [comment]
Closing as it's a dup of #192 

There's a problem with the gorilla file store, use the cookie store instead.

**Comment by lsiv568** [comment]
@markbates, I updated the example code to use the cookie store (after seeing #192).  I followed the example documented in the README to do this.  The issue is still present.  Thoughts?

**Comment by markbates** [comment]
Do your hosts match? OAuth is very finicky about that sort of thing.

**Comment by terev** [comment]
This is the issue I circumvented with my PR. It seems it was rolled back for some reason

**Comment by lsiv568** [comment]
The hosts do match.  I've tried using both localhost and a custom hostname locally via modifying my /etc/hosts file.  Not sure if the problem is due to running locally or not?  Using delve debugger I've pinpointed the problem to be with the defer taking place prior to the determining a session exists.

I updated the code to reflect @terev commit (https://github.com/markbates/goth/pull/182/commits/69abff2836b731854f6e0bd9e1aedf4924f1800a) and everything worked as expected.

**Comment by raylee** [comment]
Thank you @lsiv568 , updating gothic.go as per that commit worked for me as well.

**Comment by dexter1918** [comment]
> Thank you @lsiv568 and @terev, updating gothic.go as per that commit worked for me as well.



> The hosts do match. I've tried using both localhost and a custom hostname locally via modifying my /etc/hosts file. Not sure if the problem is due to running locally or not? Using delve debugger I've pinpointed the problem to be with the defer taking place prior to the determining a session exists.
> 
> I updated the code to reflect @terev commit ([69abff2](https://github.com/markbates/goth/commit/69abff2836b731854f6e0bd9e1aedf4924f1800a)) and everything worked as expected.



> The hosts do match. I've tried using both localhost and a custom hostname locally via modifying my /etc/hosts file. Not sure if the problem is due to running locally or not? Using delve debugger I've pinpointed the problem to be with the defer taking place prior to the determining a session exists.
> 
> I updated the code to reflect @terev commit ([69abff2](https://github.com/markbates/goth/commit/69abff2836b731854f6e0bd9e1aedf4924f1800a)) and everything worked as expected.

How can I update the code as I am facing the same issue?

**Comment by dexter1918** [comment]
> The hosts do match. I've tried using both localhost and a custom hostname locally via modifying my /etc/hosts file. Not sure if the problem is due to running locally or not? Using delve debugger I've pinpointed the problem to be with the defer taking place prior to the determining a session exists.
> 
> I updated the code to reflect @terev commit ([69abff2](https://github.com/markbates/goth/commit/69abff2836b731854f6e0bd9e1aedf4924f1800a)) and everything worked as expected.

How can I update the code?

**Comment by bentranter** [comment]
I've tried to fix this again in the latest release *[v1.67.1](https://github.com/markbates/goth/releases/tag/v1.67.1)) based on the changes in #385.

**Comment by adedaryorh** [comment]
hi @bentranter  i just reverted to this v1.67.0  but still the error persist 

Kindly find attached snippet 

![Image](https://github.com/user-attachments/assets/9650c616-3410-44ef-9fe7-d851d240362b)
