### ISSUE TITLE
Support defining which scopes to request for Github provider

### ISSUE THREAD

**Issue by cpjolicoeur** [markbates/goth#20]
Currently, the `authUrl` is hardcoded and there is no mechanism in place to provide which scopes you want to request for the user being authenticated, so by default you only get `public` access.

Would be nice to be able to configure which [Github scopes](https://developer.github.com/v3/oauth/#scopes) are desired.

**Comment by markbates** [comment]
Open a PR. Will gladly merge in a good solution.

**Comment by cpjolicoeur** [comment]
When I finalize my current modifications, I'll send it up
