### ISSUE TITLE
Update providers dropbox to v2

### ISSUE THREAD

**Issue by SuperSandro2000** [markbates/goth#204]
Dropbox Api v1 is no longer supported and simple returns error code 400.
Would you kindly update it to v2?
File using the v1 api: https://github.com/markbates/goth/blob/master/providers/dropbox/dropbox.go
https://www.dropbox.com/developers/reference/migration-guide

**Comment by adamo57** [comment]
Hey! Thanks for the issue. I'll get right on that.

**Comment by adamo57** [comment]
There might have to be some updates to the tests to prevent this from happening in the future, but that will be a separate issue. This PR, once merged, should get you moving again @SuperSandro2000
