### ISSUE TITLE
Add Go 1.10 to Travis build

### ISSUE THREAD

**Issue by bentranter** [markbates/goth#208]
As [Go 1.10](https://blog.golang.org/go1.10) was just released, we need to add support to the Travis build for testing on Go 1.10.

To do this, someone needs to:

1. Clone the repo.
2. Open the [.travis.yml](https://github.com/markbates/goth/blob/master/.travis.yml) file.
3. Between the `1.9` and `tip` values, add a value for Go 1.10. There's a gotcha here -- Travis will interpret `1.10` as either 1.1 or 1.7.1, so the 1.10 value **needs to be in quotation marks:** `"1.10"`
4. Open a [pull request](https://github.com/markbates/goth/pulls) and add this issue number in the pull request's description.

---

This is a good issue for a first-time contributor, or even someone who is new to GitHub. if you'd like to help out, please do -- I'm happy to help you if you get stuck.

**Comment by Atul9** [comment]
@bentranter I have opened up a PR for this
