### ISSUE TITLE
Use goth for Hugo or other static site authentication?

### ISSUE THREAD

**Issue by shah** [markbates/goth#225]
I was curious if anyone has used goth as a service for authenticating statically generated sites (e.g. Hugo) on Netlify or even custom hosts. The idea is that certain pages in a static site might need auth/authz and those pages would be sent to goth for authentication.

Googling around didn't seem to turn up anything so any quick pointers would be helpful

Thanks!

**Comment by bentranter** [comment]
For Netlify, using Goth is not possible, as Goth only implements the server-side Oauth2 flow. In the Netlify documentation, they mention that using their SDK with the Oauth2 implicit grant flow is possible -- you can see an example of that in [this example provided by Netlify](https://github.com/netlify/netlify-oauth-example).

For custom hosts, of course! If you're serving your own static site with Go, you can use Goth to handle the authentication with an Oauth2 provider, although you'll still need to implement session handling code to ensure the user is authenticated.

If you're looking for a way to use Goth as an out-of-the-box solution for serving authenticated static sites, then you won't find it here. That being said, there are Oauth2 plugins for popular webservers that you might be able to use. In your case, see https://caddyserver.com/docs/http.login and https://caddyserver.com/docs/http.hugo if you're interested in serving Hugo with Caddy using Oauth2.

**Comment by shah** [comment]
Thanks @bentranter I ended up using oauth2_proxy on Digital Ocean to solve this for now. You're right that Netlify wouldn't work in this case. Luckily my site is mostly internal and doesn't need high performance so I'm good for now.

**Comment by bentranter** [comment]
You're welcome @shah, glad you solved your issue 🙂 I'm going to close this, but feel free to re-open if you have any other questions.
