### ISSUE TITLE
OpenID Connect parser expects audience claim to be always single string

### ISSUE THREAD

**Issue by EvilVir** [markbates/goth#231]
Today I needed to connect Gitea, which is using goth module, with JetBrain's Hub service for authorization. I used OpenID Connect provider but found out that Hub is returning array of strings as the audience (aud) claim.

I was able to patch my instalation to support this but as this was my first ever piece of code I've seen in golang it's probably far from being perfect (for instance it only checks first element of the array, doesn't scan whole array - it's enough for connection with Hub to be working but not perfect).

So feature request here is to create proper handling of audience claims array :)

**Comment by ernestoalejo** [comment]
I use a custom OpenID Connect server implemented in Go, that uses [this library](https://godoc.org/gopkg.in/square/go-jose.v2/jwt#Claims) to serialize the audience and by default [it's a slice](https://godoc.org/gopkg.in/square/go-jose.v2/jwt#Audience). Even when having only one audience it directly serializes to a list.

You can see here:
  http://openid.net/specs/openid-connect-core-1_0.html#IDToken

> **aud**
> REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.

**Comment by bentranter** [comment]
@jesselegg We had https://github.com/markbates/goth/pull/240 to support Gitea a while ago, which improved the way we handle the audience claim (it changed it to allow both strings and slices of strings). Could you check to see if you're using the latest version of Goth?

**Comment by jesselegg** [comment]
@bentranter Oh great... I am running Gitea 1.5.2, which was pushed a couple of days ago. However, it appears that the Gopkg.toml constrains the version of goth to 1.45.5, which doesn't include this fix (looks like you landed it in 1.46.1). I will try to build a custom version of Gitea with the goth dependency updated...

**Comment by bentranter** [comment]
Looks like this is fixed as of https://github.com/go-gitea/gitea/pull/5078.

**Comment by bentranter** [comment]
Going to close this as I think it's fixed, and I'm trying to reduce the number of open issues in this repo in general. Feel free to re-open if there are more issues as of Gitea's linked update, or if this continues to be an issue with the OpenID provider.
