### ISSUE TITLE
no SESSION_SECRET environment variable is set

### ISSUE THREAD

**Issue by derblitz** [markbates/goth#232]
When running the referenced example and clicking on one of the authentication methods (e.g.: twitter), the following error appears in the terminal window:

"goth/gothic: no SESSION_SECRET environment variable is set. The default cookie store is not available and any calls will fail. Ignore this warning if you are using a different store."

Is the example still up to date?

**Comment by bentranter** [comment]
Yeah, the example is up to date. The default session store is [Gorilla's `sessions.CookieStore`](https://godoc.org/github.com/gorilla/sessions#NewCookieStore), and requires a key to be set when the store is created. This is mostly for convenience in the code for the examples. You can use any `Store` provider in your own application.

**Comment by boazj** [comment]
The default session store is created in the package init, so either set the env var externally or replace the default session store using
`gothic.Store = sessions.NewCookieStore([]byte("<your secret here>"))`

**Comment by bentranter** [comment]
This was fixed in #217.
