### ISSUE TITLE
Fetching User using Facebook returns an error because bio field is deprecated

### ISSUE THREAD

**Issue by ecuellog** [markbates/goth#241]
When getting a user using FetchUser and printing the user to the console I get: 
`OAuthException: (#12) bio field is deprecated for versions v2.8 and higher`

Issue was fixed when I deleted the bio field from the endpointProfile. 

`endpointProfile string = "https://graph.facebook.com/me?fields=email,first_name,last_name,link,id,name,picture,location"`

But maybe the authURL should include the version of facebook Oauth that is expected to work with this package.

**Comment by bentranter** [comment]
As this package is primarily for authentication, I don't see a need for the `bio` field, so I'm ok with removing it.

I don't have a Facebook account (and refuse to get one 😛), so it would awesome if someone could tackle this, verify that it works, and submit a PR.

As suggested above, the likely fix is updating line 25 of [`github.com/markbates/goth/providers/facebook/facebook.go#L25`](https://github.com/markbates/goth/blob/master/providers/facebook/facebook.go#L25) to remove the `about` field in the URL's `fields` query parameter.

**Comment by u5surf** [comment]
“bio” in User node has depricated from v2.8
https://developers.facebook.com/docs/graph-api/changelog/version2.8/#gapi-deprecate-user

But the end point in master branch of this repos is not include “bio” now. I could confirm work well facebook providers using example of this repos with default endpoint.

And, graph api uses the oldest version if you don’t indicate explicitly their version.
https://developers.facebook.com/docs/apps/versions/

Moreover, v2.6 is depricated in 7/13/2018,so
you may used v2.6 implictly which was oldest version by 7/13/2018.
https://developers.facebook.com/docs/graph-api/changelog/archive

Would you mind disclose your reproducing code of this issue?

**Comment by ecuellog** [comment]
@u5surf I had an older version of this package in my vendor folder, which had "bio" instead of "about".
