### ISSUE TITLE
LinkedIn provider - API changing by March 1 2019

### ISSUE THREAD

**Issue by baloo32** [markbates/goth#257]
Received email from LinkedIn Developers program that they are forcing migration to version 2.0 of their APIs by March 1, 2019.

This forces use of OAuth 2.0 authentication/authorization as well as changes to API endpoints and data availability from profiles.

More info at https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin

**Comment by bentranter** [comment]
Thanks for the heads up @baloo32, I'll look into it sometime in the next week or so

**Comment by mihiwarrior2** [comment]
Hi Ben, just wondering if you got a chance to look into this?

**Comment by baloo32** [comment]
I got bored on a day off - see PR https://github.com/markbates/goth/pull/279 for update to new V2 LinkedIn provider.

The changes implemented in this new version mean we no longer have access to the user.Location and user.Description fields.

I also cannot exhaustively test the mapping of FirstName and LastName for the Localized field and there preferred locale settings - in my limited testing it works correctly but have been unable to check where value is not **en_US**.

**Comment by bentranter** [comment]
Thanks a lot for this @baloo32, totally forgot about this issue until now. I'm gonna close this and cut a new release.

@mihiwarrior2, if there're any issues that you find with the updated implementation, feel free to re-open.
