### ISSUE TITLE
you must select a provider

### ISSUE THREAD

**Issue by cocodrino** [markbates/goth#264]
Hi @markbates , I'm very noob here, I'm trying to follow your tutorial http://www.metabates.com/2014/10/15/goth-multi-provider-authentication-for-go/ 

but using chi instead of gorilla 
but I get this error
**you must select a provider**

goth is intended to be used just with gorilla or can be used with chi too?

my code is this
```go

package main

import (
	"fmt"
	"github.com/go-chi/chi"
	"github.com/markbates/goth"
	"github.com/markbates/goth/gothic"
	"github.com/markbates/goth/providers/google"
	"html/template"
	"net/http"
)

func main(){
	goth.UseProviders(google.New(
		"xxx",
		"qqq",
		"http://localhost:3000/auth/google/callback"))

	r := chi.NewRouter()
	r.Get("/auth/{provider}/callback",func(res http.ResponseWriter,req *http.Request){
		user,err := gothic.CompleteUserAuth(res,req)
		if err != nil{
			fmt.Println("error ",err)
		}

		t,_ := template.New("foo").Parse(userTemplate)
		t.Execute(res,user)
	})

	r.Get("/auth/{provider}",gothic.BeginAuthHandler)
	r.Get("/", func(writer http.ResponseWriter, request *http.Request) {
		t,_:= template.New("foo").Parse(indexTemplate)
		t.Execute(writer,nil)
	})

	http.ListenAndServe(":3000",r)

}

var indexTemplate = `
<p><a href="/auth/twitter">Log in with Twitter</a></p>
<p><a href="/auth/facebook">Log in with Facebook</a></p>
<p><a href="/auth/google">Log in with Google</a></p>
`

var userTemplate=`
<p>Name: {{.Name}}</p>
<p>Email: {{.Email}}</p>
<p>NickName: {{.NickName}}</p>
<p>Location: {{.Location}}</p>
<p>AvatarURL: {{.AvatarURL}} <img src="{{.AvatarURL}}"></p>
<p>Description: {{.Description}}</p>
<p>UserID: {{.UserID}}</p>
<p>AccessToken: {{.AccessToken}}</p>
`



```

thank you so much

**Comment by bentranter** [comment]
Hey @cocodrino,

You can use Chi as a router, although the routes with the `/auth/{provider}` and `/auth/{provider}/callback` routes won't work as expected with Chi.

Internally, Chi parses the `{provider}` variable differently that Gorilla Mux or Pat. As a result, Gothic doesn't know how to read the value of this variable in its `gothic.CompleteUserAuth` and `gothic.BeginAuthHandler` functions, so you get the "you must select a provider" error you're seeing here.

The easiest way to fix this for Chi is to change the way you setup your URLs. If you pass the provider name via a query parameter rather than a path variable, it'll work. I've modified your code to work with Chi, so please see the code below.

```go
package main

import (
	"fmt"
	"html/template"
	"net/http"
	"os"

	"github.com/go-chi/chi"
	"github.com/markbates/goth"
	"github.com/markbates/goth/gothic"
	"github.com/markbates/goth/providers/google"
)

func main() {
        // Note that the redirect URL is different here than in your original code.
	goth.UseProviders(google.New(
		os.Getenv("GOOGLE_KEY"),
		os.Getenv("GOOGLE_SECRET"),
		"http://localhost:3000/auth/callback?provider=google"))

	r := chi.NewRouter()
	r.Get("/auth/callback", func(res http.ResponseWriter, req *http.Request) {
		user, err := gothic.CompleteUserAuth(res, req)
		if err != nil {
			fmt.Println("error ", err)
		}

		t, _ := template.New("foo").Parse(userTemplate)
		t.Execute(res, user)
	})

	r.Get("/auth", gothic.BeginAuthHandler)
	r.Get("/", func(writer http.ResponseWriter, request *http.Request) {
		t, _ := template.New("foo").Parse(indexTemplate)
		t.Execute(writer, nil)
	})

	http.ListenAndServe(":3000", r)

}

// Note that the URLs to authenticate with the various providers are different as
// well.
var indexTemplate = `
<p><a href="/auth?provider=twitter">Log in with Twitter</a></p>
<p><a href="/auth?provider=facebook">Log in with Facebook</a></p>
<p><a href="/auth?provider=google">Log in with Google</a></p>
`

var userTemplate = `
<p>Name: {{.Name}}</p>
<p>Email: {{.Email}}</p>
<p>NickName: {{.NickName}}</p>
<p>Location: {{.Location}}</p>
<p>AvatarURL: {{.AvatarURL}} <img src="{{.AvatarURL}}"></p>
<p>Description: {{.Description}}</p>
<p>UserID: {{.UserID}}</p>
<p>AccessToken: {{.AccessToken}}</p>
`
```

**Comment by cocodrino** [comment]
thank you so much @bentranter , works perfect!!!...have a nice day :+1:

**Comment by bentranter** [comment]
You're welcome @cocodrino, you as well 🙂

**Comment by dustin-decker** [comment]
Another way to solve this is to set the context value with Chi's URLParam value:


```
func Callback(res http.ResponseWriter, req *http.Request) {
	// make provider available to the handler
	provider := chi.URLParam(req, "provider")
	req = req.WithContext(context.WithValue(context.Background(), "provider", provider))
	
        user, err := gothic.CompleteUserAuth(res, req)
	if err != nil {
		fmt.Fprintln(res, err)
		return
	}
	
	...
```

**Comment by r6m** [comment]
another option would be adding the `provider` query param.

```go
// route: GET /auth/{provider}
func handleAuth(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	q.Add("provider", chi.URLParam(r, "provider"))
	r.URL.RawQuery = q.Encode()

	gothic.BeginAuthHandler(w, r)
}
```

**Comment by yanlkm** [comment]
Hello, I'm trying to use the goth oauth for github authentification, 
Whatever I'm trying to do, I got the same error of provider missing, Can someone help me ? 

`package oauth

import (
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/sessions"
	"github.com/markbates/goth/gothic"
	"github.com/markbates/goth"
	"github.com/markbates/goth/providers/github"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"chat-app/pkg/user"
	"chat-app/pkg/utils"
)

func ConfigureProviders() {

	key := os.Getenv("GITHUB_CLIENT_ID")
	secret := os.Getenv("GITHUB_CLIENT_SECRET")
	callbackURL := os.Getenv("BASE_URL") + "/auth/github/callback"

	// Initialize GitHub provider
	goth.UseProviders(
		github.New(key, secret, callbackURL),
	)
}

func GithubAuthHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		// Store the session in the cookie
		store := sessions.NewCookieStore([]byte("secret"))
		gothic.Store = store

		// debug
		fmt.Println("Store:", gothic.Store)
		// debug
		fmt.Println("Providers:", goth.GetProviders())

		// Start authentication
		gothic.BeginAuthHandler(c.Writer, c.Request)

		// debug
		fmt.Println("Authentification avec GitHub")
	}
}

func GithubAuthCallbackHandler(userService user.UserService) gin.HandlerFunc {
	return func(c *gin.Context) {
		// Continue with GitHub authentication processing
		gothUser, err := gothic.CompleteUserAuth(c.Writer, c.Request)
		if err != nil {
			// Handle the error here, for example, display an error message to the user
			fmt.Println("Erreur: ", err)
			return
		}

		// debug
		fmt.Println("gothUser:", gothUser)
		// Check if the user already exists in the database
		existingUser, err := userService.GetUserByUsername(c.Request.Context(), gothUser.Name)
		if err != nil {
			// Handle the error of user lookup
			return
		}

		if existingUser != nil {
			// The user already exists, log them in
			// Generate the JWT token
			objectID, err := primitive.ObjectIDFromHex(existingUser.ID)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "Impossible d'obtenir l'utilisateur"})
				return
			}
			token, err := utils.GenerateToken(&existingUser.Username, &objectID)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "Impossible de générer le jeton"})
				return
			}
			// Set the token in the cookie
			c.SetCookie("token", token, 72*3600, "/", "localhost", false, true)
			// Set the token in the header
			c.Header("Authorization", token)

			// Send the token in response
			c.JSON(http.StatusOK, gin.H{"status": true, "token": token, "message": "Vous êtes connecté avec GitHub!"})
		} else {
			// The user does not exist yet, create them
			newUser := user.User{
				Username:  gothUser.Name,
				Email:     gothUser.Email,
				CreatedAt: time.Now(),
				UpdatedAt: time.Now(),
			}

			err := userService.CreateUser(c.Request.Context(), &newUser)
			if err != nil {
				// Handle the error of user creation
				return
			}

			// User created, log them in
			// Generate the JWT token
			objectID, err := primitive.ObjectIDFromHex(newUser.ID)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "Impossible d'obtenir l'utilisateur"})
				return
			}
			token, err := utils.GenerateToken(&newUser.Username, &objectID)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "Impossible de générer le jeton"})
				return
			}
			// Set the token in the cookie
			c.SetCookie("token", token, 72*3600, "/", "localhost", false, true)
			// Set the token in the header
			c.Header("Authorization", token)

			// Send the token in response
			c.JSON(http.StatusOK, gin.H{"status": true, "token": token, "message": "Vous êtes connecté avec GitHub!"})
		}
	}
}
`

Here is my router code : 
`	// Initialize the goth providers
	oauth.ConfigureProviders()
	// oauth routes
	r.GET("auth/github",
		oauth.GithubAuthHandler())
	r.GET("auth/github/callback",
		oauth.GithubAuthCallbackHandler(userService))
	// TODO: Delete favicon route
	r.StaticFile("/favicon.ico", "./favicon.ico")`

**Comment by qbart** [comment]
For future readers, goth has the ability to override how provider is fetched, so for chi it could be:
```go
	gothic.GetProviderName = func(req *http.Request) (string, error) {
		provider := chi.URLParam(req, "provider")
		if provider != "" {
			return provider, nil
		}
		return "", fmt.Errorf("no provider specified")
	}
```
the best would be to dig into source code of original function to see how it works and make sure when overriding you don't miss any functionality

**Comment by muhammadyasir-dev** [comment]
i am sick of this issue  is this problem in library or other stuff . 
i have this issue:  gothic.BeginAuthHandler no value used as (w,r) used value 

`` func SigninWithGoogle(w http.ResponseWriter, r *http.Request) {
	// Start the authentication process
	url, err := gothic.BeginAuthHandler(w, r)
	if err != nil {
		http.Error(w, "Failed to start authentication", http.StatusInternalServerError)
		return
	}
	http.Redirect(w, r, url, http.StatusTemporaryRedirect)
}
```
