### ISSUE TITLE
VK provider added twice in example

### ISSUE THREAD

**Issue by tsdtsdtsd** [markbates/goth#267]
VK provider added here:
https://github.com/markbates/goth/blob/6120c3bdb1bf48e64c7a4d385f164d63e0f65d4e/examples/main.go#L117

and also 2 lines below:
https://github.com/markbates/goth/blob/6120c3bdb1bf48e64c7a4d385f164d63e0f65d4e/examples/main.go#L119

**Comment by bentranter** [comment]
I think this is from the PR that added support for the Yandex provider, probably due to a bad rebase/GitHub making it difficult to view all changes throughout the PR review process.

If anyone would like to submit a PR for this, I'd be happy to merge it.
