### ISSUE TITLE
GAE compatibility (urlfetch)

### ISSUE THREAD

**Issue by RubenN** [markbates/goth#27]
I'd like to use this on app engine.
What would the best way be to get the proper (urlfetch) compatible Transport in?
(FetchUser uses the default http.Get)

The result i got was: 
<code>
Post https://accounts.google.com/o/oauth2/token: http.DefaultTransport and http.DefaultClient are not available in App Engine. See https://cloud.google.com/appengine/docs/go/urlfetch/
<code>

**Comment by tylerb** [comment]
The pattern for this kind of thing thus far has been callback functions that the user can set to provide customized functionality.

I would recommend having an `GetClient()` function that returns the `http.Client` to use for fetching the URL. By default, this should return a new client, but it could be overridden by calling code (see `GetProviderName`) to return the `urlfetch.Client` for use on App Engine.

This also has the added benefit of not strongly binding `goth` to any app engine code or logic.

@markbates thoughts?

**Comment by RubenN** [comment]
Sounds like a valid solution if it is in line with Mark's thoughts.

**Comment by markbates** [comment]
I don't use GAE, so I'm not sure of the exact nature of the problem, so I'll leave this to Tyler's discretion, as he seems to have a handle on this.

**Comment by tylerb** [comment]
Sounds good. The approach I posted above should work just fine. @RubenN do you want to go ahead and implement this, then submit a PR?

**Comment by RubenN** [comment]
Ok

**Comment by RubenN** [comment]
It turned out to be even simpler and doesn't require code changes.
The key is to change the default http client like this:

<code>
	http.DefaultClient = &http.Client{
    	Transport: &urlfetch.Transport{Context: c},
	}
	http.DefaultTransport = &urlfetch.Transport{Context: c}
</code>

**Comment by oyvindsk** [comment]
For the record, this does not work anymore with newer versions of oauth2. It looks like it should be unnecessary now, but I  can't get it to work at all with oauth2 released after March sometime (it's obvious which commit it is..)

Works if you revert back to before that commit in March and use @RubenN 's sollution

**Comment by markbates** [comment]
As before, I don't use GAE, so I can't produce. However, @oyvindsk if you can reproduce and know a fix please submit a PR so we can close this. Thanks.
