### ISSUE TITLE
Not setting auth cookie

### ISSUE THREAD

**Issue by kaihendry** [markbates/goth#270]
I expected Goth to set a cookie and it doesn't, so I am very puzzled.

https://github.com/unee-t/internal-github-login/tree/goth
https://github.dev.unee-t.com/

It doesn't appear to. Furthermore I don't understand how you are supposed to validate the user's token is authorized. Are there more worked out examples, than https://github.com/markbates/goth/blob/master/examples/main.go please? Couldn't find one via Github Search.

Thank you in advance,

**Comment by is2ei** [comment]
@kaihendry 
I guess Goth's cookie is for internal use.

https://github.com/markbates/goth/commit/9885e531187c65b2228660f30074bde565f93d3f#diff-61a370b1e72c6044c498a0fd700448c9

I think the "try to get the user without re-authenticating" part in the example.go does not work anymore... 

https://github.com/markbates/goth/commit/a1fc3f65a0a8229b5e597a542b0fccedddbf71e1

**Comment by baloo32** [comment]
As @is2ei says - the goth cookies are internal and only used as part of the auth flow. Your own application must maintain its own session/authentication state from the data provided back after calling gothic.CompleteUserAuth.

Suggest storage of AccessToken and (possibly) RefreshToken to allow subsequent use if you need to call the IdP to obtain further info.

**Comment by bentranter** [comment]
To wrap this issue up, yeah, the Goth cookie set by the `gothic` package is used to store and later validate the nonce used in the `state` parameter. It shouldn't really be used for authentication, but I understand that's not really obvious.

It's something I'd like to change in the future, but this package has been around for a long time and I don't want to change any of the APIs. I think moving forward, I'd like to make it more clear that Goth should _only_ be used for identity verification, and not include any uses cases related to getting API tokens or using it as a full blown authentication solution.
