### ISSUE TITLE
Add support for Apple Oauth

### ISSUE THREAD

**Issue by tylerstillwater** [markbates/goth#290]
My company has need of the new "Sign in with Apple" functionality.

https://developer.apple.com/sign-in-with-apple/

I'll give it a stab and submit a PR at some point soon.

**Comment by juanscolari** [comment]
@tylerb do you have any WIP/Draft for this feature to show us?

**Comment by tylerb** [comment]
Not yet. I'm hoping to get something up this week.

**Comment by guilhermehubner** [comment]
@tylerb any update on it?

**Comment by tylerb** [comment]
Unfortunately not. Things have been crazy at work and I've not had a chance to get to this. Still fully intend to, though. One of our other developers may jump on it.

**Comment by wunderkind2k1** [comment]
Isn't this done?

**Comment by wunderkind2k1** [comment]
I think this issue can be closed - what do you guys think?

**Comment by yaronius** [comment]
@markbates @bentranter please close
