### ISSUE TITLE
decodeJWT should decode base64url

### ISSUE THREAD

**Issue by oscarlofwenhamn** [markbates/goth#316]
Since JSON Web Tokens (afaik) are encoded using base64url by default, the decoding method should reflect this. 

https://github.com/markbates/goth/blob/8a9b88125edf10f2441ec2cc9aa6f40c39e50186/providers/openidConnect/openidConnect.go#L398-L402

Could instead be simply 

```
decodedPayload, err := base64.URLEncoding.WithPadding(base64.NoPadding).DecodeString(encodedPayload)
```
since base64url has no padding.

Alternatively, a check to correct base64url-encoded tokens that translates them to a padded standard encoded string could be introduced, whichever is preferred?

**Comment by chnliyong** [comment]
Good job!
I just found this problem（using `gitea` which depends `goth`).

**Comment by chnliyong** [comment]
@oscarlofwenhamn I just noticed there's one line in `base64.go`
```go
var RawURLEncoding = URLEncoding.WithPadding(NoPadding)
```

**Comment by oscarlofwenhamn** [comment]
@chnliyong Same here, also found it while using Gitea, and an external identity provider which sends JWTs. 

Most often it would work, but for a small number of users their JWT token includes the URL safe characters `-` and `_` instead of `+`and `/`, causing a decoding error. Finally we figured out where the problem stemmed, and now we would need it fixed here in upstream so we don't have to write our own authentication flow and thus get too detached from the Gitea upstream.
