### ISSUE TITLE
[Feature Request]Adding support for Keycloak

### ISSUE THREAD

**Issue by leopku** [markbates/goth#319]
Keycloak is an Open Source Identity and Access Management solution for modern Applications and Services.
The repo is [here](https://github.com/keycloak/keycloak).

**Comment by chnliyong** [comment]
As **Keycloak** support standard `OpenID Connect`, the `openidConnect` provider works. 

The only problem now is the `openidConnect` has a `decodeJWT` bug pending fix by this issue: https://github.com/markbates/goth/pull/317

**Comment by oscarlofwenhamn** [comment]
#317 has been merged and the connected issue #316 closed.

**Comment by bentranter** [comment]
Closing this, as it appears this has been resolved. Feel free to reopen if this continues to be an issue.
