### ISSUE TITLE
undefined: SetCurrentUser undefined: Authorize

### ISSUE THREAD

**Issue by zhangfuwen** [markbates/goth#320]
I generated a new buffalo project, and ran `buffalo-goth goth-auth github`. I first encountered an error which said: 

```gobuffalo/buffalo@v0.14.11/render/template_helpers.go:21:23: cannot use "github.com/gobuffalo/helpers/tags".JS (type func(string, "github.com/gobuffalo/tags/v3".Options) "html/template".HTML) as type func(string, "github.com/gobuffalo/tags".Options) "html/template".HTML in field value```

then I `go get -u` to update everything. Then I got this message:

```
actions/app.go:67:11: undefined: SetCurrentUser
actions/app.go:68:11: undefined: Authorize
actions/app.go:69:23: undefined: Authorize
actions/app.go:72:19: undefined: AuthDestroy
actions/app.go:73:24: undefined: Authorize
```

I am new to buffalo and buffalo-goth. As I understood, SetCurrentUser and Authorize are expected to be provided by buffalo but now they disappear. 

Or am I expected to implement these method by myself?

**Comment by chnliyong** [comment]
Maybe you should post this issue to the buffalo project.

I also new to `buffalo` too. Maybe you can try the `buffalo fix` command. I use the `buffalo-goth` to generate OpenID Connect(provider `openid-connect`) code a few days ago, there's no error occurred.

**Comment by bentranter** [comment]
Hey @zhangfuwen, like @chnliyong said, I think you're better off posting this issue on the buffalo project. I'm not a buffalo user myself, and it looks like the error you have is on buffalo's side, so you may be able to get more help there. I'm going to close this for now, but feel free to reopen if you think this is an issue with Goth.
