### ISSUE TITLE
[Feature Request] Adding Strava Provider

### ISSUE THREAD

**Issue by nedenwalker** [markbates/goth#324]
Strava is Athletics tracking with Social Media features built in: https://www.strava.com

Authentication information: https://developers.strava.com/docs/authentication/

PR: https://github.com/markbates/goth/pull/323

**Comment by bentranter** [comment]
I've merged the PR and created v1.62.0 which includes this, so I'm going to close this issue. Thanks for your contribution @nedenwalker!

**Comment by nedenwalker** [comment]
Sweetness! Thank you :)
