### ISSUE TITLE
Go report card

### ISSUE THREAD

**Issue by bvwells** [markbates/goth#334]
I noticed a couple of minor typos (#333) and was wondering whether it is worth adding go report card as I suspect that this would have highlighted these minor issues. 

More than happy to open a PR if you want it added.

P.S. Nice repo, it's a really helpful resource!

**Comment by bvwells** [comment]
Added a PR, but more than happy to abandon if this is not needed.

**Comment by bentranter** [comment]
I think it's useful, especially for me to track any changes over time. Thanks for that PR!
