### ISSUE TITLE
CallbackURL change at auth time?

### ISSUE THREAD

**Issue by jum** [markbates/goth#345]
I am having the problem that the CallbackURL is not really fixed until being called in the context of the login, e.g. while in the handler for the button performing the login. Currently each of the providers has it's own implementation of that field and it is not exposed to the generic Provider interface, making it a pain to change at runtime. Would it be acceptable to move that to the generic Provider interface (although not all providers need it)?

**Comment by jum** [comment]
Ok, after some more studying of the code I see that the CallbackURL cannot really be changed after initializing the provider. I am thus postponing the allocation of my providers until request time, where I am sure about the CallbackURL.

**Comment by hxgdzyuyi** [comment]
> Ok, after some more studying of the code I see that the CallbackURL cannot really be changed after initializing the provider. I am thus postponing the allocation of my providers until request time, where I am sure about the CallbackURL.

like this?


```
func handleAuth(w http.ResponseWriter, r *http.Request) {
    // 从请求中获取 redirect_uri
    redirectURI := r.FormValue("redirect_uri")

    provider := github.New(
        "YOUR_CLIENT_KEY",
        "YOUR_CLIENT_SECRET",
        "http://localhost:3000/auth/github/callback",
        redirectURI,
    )

    gothic.BeginAuthHandler(w, r, provider)
}
```
