### ISSUE TITLE
state for all providers?

### ISSUE THREAD

**Issue by laicosly** [markbates/goth#35]
does goth have a common story for setting additional session params for the providers that do not support oauth2's state parameter?

**Comment by laicosly** [comment]
a twitter response suggested adding params to the "oauth_callback" callback to track state, but since goth providers use sessions, maybe that's the ideal place to lookup a state value in oauth callbacks?

**Comment by markbates** [comment]
The point of the session is track stuff across all of the requests, so that would be the place to put any of that type of data.

**Comment by laicosly** [comment]
@markbates  right.  is there a recommended approach to using the provider sessions?  I want to track a property with the twitter auth session to be used on successful callbacks.  there doesn't look like any place to add that to the session, or any convenience methods.

**Comment by markbates** [comment]
You would have to add some convenience methods to the API to let you hook into it. Shouldn't be that hard though. I would welcome the PR.

**Comment by laicosly** [comment]
@markbates   thanks, that's what I was wondering.
