### ISSUE TITLE
State validation when using "sign in with apple" (sometimes) broken

### ISSUE THREAD

**Issue by wunderkind2k1** [markbates/goth#360]
# Description
If I try to sign in with apple and the scopes "name" and "email", the login is not working.

# Analysis/ Fix
Apple uses a POST callback, when we use "name" or "email" scope. This results in the state encoded in the form parameter instead of url. The current implementation fo GetState does not change its behaviour if the callback is sent with POST instead of GET. This results in an error in the state comparison and a broken login.

**Comment by newro** [comment]
Hi, I'm interesting this issue.
This issue seems to be resolving, when will it merge?

**Comment by yaronius** [comment]
Hi @markbates @bentranter, any news on this? This is a nasty issue. And the fix is quite simple and obvious.

**Comment by bentranter** [comment]
Released in [v1.67.0](https://github.com/markbates/goth/releases/tag/v1.67.0).
