### ISSUE TITLE
Add support for Mastodon OAuth

### ISSUE THREAD

**Issue by OmmyZhang** [markbates/goth#362]
Doc: https://docs.joinmastodon.org/client/authorized/

**Comment by OmmyZhang** [comment]
some key endpoint:
auth: `<domain>/oauth/authorize`
token: `<domain>/oauth/token`
userinfo: `<domain>/api/v1/accounts/verify_credentials`

The scopes could be `[read]` or `[read:accounts]`.

**Comment by techknowlogick** [comment]
I've just created a PR for this.

**Comment by bentranter** [comment]
Thanks @techknowlogick. I'm going to fix our CI process (it seems that Travis doesn't want to report the status anymore), and then I'll cut a new release with your change.

**Comment by techknowlogick** [comment]
Thanks @bentranter :) If you ever need any help (reviewing PRs, fixing CI, etc..) let me know. I'm one of the project leads of Gitea and we make pretty heavy use of Goth so I'm happy to contribute back.

**Comment by bentranter** [comment]
Released in v1.65.0. And thanks @techknowlogick – I actually don't have admin privileges to the repo, so I can't add new collaborators, but I would love to add you. I'll see if I can contact Mark to get you added.

**Comment by makeworld-the-better-one** [comment]
Heads-up that this is not mentioned on the README
