### ISSUE TITLE
Complete upgrade to Go 1.15

### ISSUE THREAD

**Issue by bentranter** [markbates/goth#368]
### Overview

According to our `go.mod` file, the supported version is Go 1.14. We should update to it to 1.15. 

### How to fix it

1. Clone this repo.
2. Ensure you're running Go 1.15.
3. Update the Go version to 1.15 in `go.mod`.
4. Open a pull request with your changes.

**Comment by techknowlogick** [comment]
1.15 is already in the go version matrix of Github Actions CI workflow

**Comment by bentranter** [comment]
Thanks @techknowlogick, I must've been thinking about a different repo when I wrote the description. I'll update it so that the only change necessary is in the `go.mod` file.

**Comment by suntala** [comment]
Hi 👋 
I would like to work on this issue. May I please be assigned to it?

**Comment by bentranter** [comment]
Sure @suntala, I'll assign this to you, although this type of issue tends be popular during Hacktoberfest, so I can't guarantee that someone else won't work on it before you do.

**Comment by suntala** [comment]
Thanks @bentranter!
