### ISSUE TITLE
Goth fails gofmt

### ISSUE THREAD

**Issue by bentranter** [markbates/goth#369]
### Overview

The repo currently fails the `gofmt` check, meaning that the codebase doesn't adhere to the Go coding standards.

### How to fix it

1. Clone this repo.
2. Run `gofmt -s -w ./` from the root of the repo.
3. Open a pull request with your changes.
4. **BONUS** Update our GitHub Actions CI workflow to include a `gofmt` check. This will require you to add a new step. Something like,

```yaml
 - name: Format
   run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
 ```
 _may_ work, but I haven't tested it personally.

**Comment by mukulrawat1986** [comment]
Hi, I would like to work on this.

**Comment by techknowlogick** [comment]
@mukulrawat1986 please see #371 there is already an existing PR for this.
