### ISSUE TITLE
Add provider for OuraRing

### ISSUE THREAD

**Issue by JoshKCarroll** [markbates/goth#376]
Add provider for the OuraRing API, which uses OAuth2

https://cloud.ouraring.com/docs/authentication

**Comment by JoshKCarroll** [comment]
In case this doesn't get merged and someone else sees it later, I have also written a minimal provider which can be imported and used with this library, see `github.com/qntfy/goth @ v0.0.8`

**Comment by bentranter** [comment]
Released in [v1.66.0](https://github.com/markbates/goth/releases/tag/v1.66.0)
