### ISSUE TITLE
Okta available as a provider but missing in README.md

### ISSUE THREAD

**Issue by brittonhayes** [markbates/goth#378]
Hey there 👋 Noticed that [Okta is an available provider as listed in the GoDocs]( https://pkg.go.dev/github.com/markbates/goth/providers/okta) and [has an associated example](https://github.com/markbates/goth/search?q=okta) but it isn't documented in the [README.md](https://github.com/markbates/goth/blob/master/README.md). 

Love the project! Here's a [relevant PR to fix this](https://github.com/markbates/goth/pull/379). Just wanted to give a heads up in case others saw the list and didn't pick goth because they didn't see Okta in the list of options.

**Comment by tn185075** [comment]
@brittonhayes Were you able to use OKTA provider successfully?

**Comment by brittonhayes** [comment]
@tn185075 Hey! I'm honestly not sure. It's been so long since I was involved in the project that I just don't remember.

Sorry I can't be more helpful😕 Just didn't wanna leave you hangin. Hope you're able to get this working!

**Comment by tn185075** [comment]
Thanks for the reply.
