### ISSUE TITLE
How to set gothic.State

### ISSUE THREAD

**Issue by flimzy** [markbates/goth#38]
I'm a bit puzzled about the intended use of `gothic.Store`:

    // Store can/should be set by applications using gothic. The default is a cookie store.
    var Store sessions.Store

    func init() {
	if Store == nil {
		Store = sessions.NewCookieStore([]byte(AppKey))
	}
    }

According to my understanding of Go package initialization (and some rudimentary tests I've done), there's no way to set gothic.Store before init() runs.

Maybe that's not considered expressly "harmful," since it just means that sessions.NewCookieStore() is run needlessly, then the result is discarded (as soon as gothic.Store is set to something else), but it doesn't appear to be the intention of the code.

Or am I missing something?

**Comment by markbates** [comment]
If you're asking if the `if` statement could be removed, you are correct.

The reason the `init` function is there is to make sure there is always a `sessions.Store`, even if the user doesn't want to create one.

If the user does create their own store the one from the `init` function is thrown away, but that's fine, there's barely any cost to initializing it, and it's better to have one initialized than not.

**Comment by flimzy** [comment]
That makes sense, as far as it goes.  I guess it's just a little non-obvious.  Especially with the comment about replacing AppKey -- this seems to indicate that setting `gothic.Appkey` ought to actually do something.  :)
