### ISSUE TITLE
What is the best practice to take goth working with SPA project especially for callback after login?

### ISSUE THREAD

**Issue by leopku** [markbates/goth#381]
As of more and more separation of front-end and backend, SPA was more popular today.
After trying some times, I found some bad smell in my process when jumping back to callback url.

I tried two solutions,
1. Callback url was provided by goth. 
  Firstly jumping back to goth and complete user auth. Then goth jump back to SPA with customized JWT token in URL params.
  User would got a very long url with token in params. I think it's bad smell.
2. Callback url was provided by SPA. 
  But this solution had a problem. When invoking goth to complete user auth using Ajax call in SPA, goth would check _gothic_session. It troubled me many days.

Which one is the best practice?
Or even more another best practice?

**Comment by AtanasSarafov** [comment]
Why is this issue closed? Is it resolved somehow?

**Comment by leopku** [comment]
Finally I used the first method with little change:

Redirecting to SPA with code **but not token**,  then SPA request with code to get really token.
