### ISSUE TITLE
Facebook not returning an email

### ISSUE THREAD

**Issue by faeronsayn** [markbates/goth#39]
I'm having trouble getting facebook to return an email. It shows that I've given permission to the app for my email, but the user response doesn't have the email filled in. I'm wondering if we're just not setting the email properly?

**Comment by tylerb** [comment]
I don't have a Facebook account, so this isn't one I can validate easily. 




@markbates can you take a look?

**Comment by faeronsayn** [comment]
So making a new facebook account does indeed return an email. So, it might just be my facebook account. So i'll just close this issue.
