### ISSUE TITLE
App Engine Fix: Supply a context to oauth2 Export()

### ISSUE THREAD

**Issue by oyvindsk** [markbates/goth#40]
This is what I have so far. It works, but as a Golang and App Engine noob, I'm guessing some else can come up with a nicer solution?  https://github.com/oyvindsk/goth/commit/6e8230b7bd108673a5534c8b95cae0d7f05f5b17
It's a pain to implement that callback as you an see in the comment.

_Why:_
The oauth2 module changed and it now handles the http.DefaultClient stuff in App Engine compatible way. So for oauth2 you no longer have to set http.DefaultClient and http.DefaultTransport as in Issue #27 . (goth using the default http.Client is another issue..)

But, you do have to supply a  context.Context to oauth2 in Exchange() as in the above commit.

_Related:_ 
Pull #30 
https://groups.google.com/forum/#!searchin/google-appengine-go/oauth2/google-appengine-go/5H2Ra85cu1M/e57iIRivEgAJ

**Comment by felixLam** [comment]
I have submitted a PR that fixes the use of the DefaultClient (it makes it at least configurable).
https://github.com/markbates/goth/pull/87

**Comment by bentranter** [comment]
This should be fixed as of https://github.com/markbates/goth/pull/87, but I'm going to try this on AppEngine myself and see if I can either document how it'd work on AppEngine, or add it to a separate example in the examples folder.

**Comment by bentranter** [comment]
Closing this due to age, feel free to re-open if it's still an issue.
