### ISSUE TITLE
discord oauth2 always forces authorization prompt (even if previously approved)

### ISSUE THREAD

**Issue by lrstanley** [markbates/goth#401]
the current Discord oauth2 flow does not provide a `prompt` GET parameter during the redirect to Discord. As such, the default flow for Discord is to always prompt to validate the flow, even if the user has **already previously approved the provided scopes**.

I don't think this should be the default behavior for this library. If the user has already approved the scopes, it should just seamlessly redirect back to the application.

I didn't see [in the Discord docs](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant) that it actually defaults to `prompt=consent`, but intercepting the request, it looks as though the lack of `prompt` does default to `consent`. Also see:

> `prompt` controls how the authorization flow handles existing authorizations. If a user has previously authorized your application with the requested scopes and prompt is set to `consent`, it will request them to reapprove their authorization. If set to `none`, it will skip the authorization screen and redirect them back to your redirect URI without requesting their authorization. For passthrough scopes, like `bot` and `webhook.incoming`, authorization is always required.

I.e:

- If scopes haven't been previously approved, prompt
- If sensitive scopes (`bot` & `webhook.incoming`) are used, ignore `prompt` parameter, and provide consent dialog
- If all scopes have already been approved previously, auto-redirect back to application

Since we can technically do the redirect to Discord in our own code, and append `&prompt=none` to the URL (hacky, but works...), this issue is just for the discussion around changing that default to automatically do this.

This change should be non-breaking, as the response from the oauth2 flow doesn't seem to change if the re-approve vs previously-approved.

Thoughts?

I can submit a PR if 👍

**Comment by FluffyKitty0** [comment]
This would be great, I'm going to get a PR sent in with this change.  It seems that not much is going on right now (last commit was quite some time ago) but this is a relatively simple change, hopefully we can get it pushed through.

**Comment by lrstanley** [comment]
I ended up moving away from goth and manually going through the oauth flow with discord, since I only need Discord auth. I do something along the lines of:

```
config.AuthCodeURL(	
    state,
    oauth2.AccessTypeOffline,
    oauth2.SetAuthURLParam("prompt", "none"),
```

where config is the oauth2 client. I think goth uses the 
same oauth2 client in some form (on my phone atm so can't easily check). maybe something similar could be done?

**Comment by FluffyKitty0** [comment]
It seems to be something around this line:

https://github.com/markbates/goth/blob/19c3059c9ed44995940c8222a8eda10f6b604e01/providers/discord/discord.go#L190

Possibly some kind of get parameter declaration, not sure...

Once again, if anyone more familiar with Goth could chime in, the help would be greatly appreciated.  I'm not familiar with how everything here is designed and I don't have time to dive into this right now.

**Comment by stipkovich** [comment]
> the current Discord oauth2 flow does not provide a `prompt` GET parameter during the redirect to Discord. As such, the default flow for Discord is to always prompt to validate the flow, even if the user has **already previously approved the provided scopes**.
> 
> I don't think this should be the default behavior for this library. If the user has already approved the scopes, it should just seamlessly redirect back to the application.
> 
> I didn't see [in the Discord docs](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant) that it actually defaults to `prompt=consent`, but intercepting the request, it looks as though the lack of `prompt` does default to `consent`. Also see:
> 
> > `prompt` controls how the authorization flow handles existing authorizations. If a user has previously authorized your application with the requested scopes and prompt is set to `consent`, it will request them to reapprove their authorization. If set to `none`, it will skip the authorization screen and redirect them back to your redirect URI without requesting their authorization. For passthrough scopes, like `bot` and `webhook.incoming`, authorization is always required.
> 
> I.e:
> 
> * If scopes haven't been previously approved, prompt
> * If sensitive scopes (`bot` & `webhook.incoming`) are used, ignore `prompt` parameter, and provide consent dialog
> * If all scopes have already been approved previously, auto-redirect back to application
> 
> Since we can technically do the redirect to Discord in our own code, and append `&prompt=none` to the URL (hacky, but works...), this issue is just for the discussion around changing that default to automatically do this.
> 
> This change should be non-breaking, as the response from the oauth2 flow doesn't seem to change if the re-approve vs previously-approved.
> 
> Thoughts?
> 
> I can submit a PR if 👍

Finally found a thread regarding this issue. Thanks!

I'm trying to find where to add this `&prompt=none`. I've added it to the `$authorizeURL = 'https://discord.com/api/oauth2/authorize/?prompt=none';` line in my script to no avail. I still get the prompt every time. Can you advise where, precisely, we add the `&prompt=none`?

Thanks!

Discord newbie,

Aaron

**Comment by lrstanley** [comment]
Make sure the URL it is trying to redirect to actually has it, and if the parameters are malformed in some way. Providing it in the authoriseURL may break the GET parameters.

Just went back through my code before I refactored, and this is what I had, which I believe worked without issue, though a bit hacky:

```go
        // Don't use this, as we're handling the logic to redirect the user ourselves.
	// gothic.BeginAuthHandler(w, gothic.GetContextWithProvider(r, "discord"))

	url, err := gothic.GetAuthURL(w, gothic.GetContextWithProvider(r, "discord"))
	if err == nil {
		// See: https://github.com/markbates/goth/issues/401
		url += "&prompt=none"

		http.Redirect(w, r, url, http.StatusTemporaryRedirect)
		return
	}
```

This will essentially take the generated URL, and appends the `prompt` GET parameter, rather than having to provide the authorizeURL yourself.
