### ISSUE TITLE
The jwt-go dependency is no longer maintained w/ vulernabilities and should be migrated to golang-jwt/jwt or similar

### ISSUE THREAD

**Issue by duncan-truss** [markbates/goth#412]
GitHub has released a [security vulnerability](https://github.com/advisories/GHSA-w73w-5m7g-f7qc) affecting the unmaintained [jwt-go](https://github.com/dgrijalva/jwt-go) library.  Seeing as it won't be getting any patches it probably makes sense to migrate to the cloned successor [golang-jwt/jwt](https://github.com/golang-jwt/jwt) version 3.2.1

**Comment by bentranter** [comment]
Fixed in [v1.68.0](https://github.com/markbates/goth/releases/tag/v1.68.0). Thanks for the report!

**Comment by duncan-truss** [comment]
That was quick, thanks for addressing it!
