### ISSUE TITLE
SCS Store Support?

### ISSUE THREAD

**Issue by FM1337** [markbates/goth#422]
Is it possible in the future that support for scs (https://github.com/alexedwards/scs) could be added so that you could use that library rather than being forced to use gorilla?

**Comment by FM1337** [comment]
Nvm, I'm dumb. Took 14 days to figure out actually how to properly use this.

**Comment by delaneyj** [comment]
![image](https://github.com/markbates/goth/assets/438252/7fa63413-f6a3-4995-9cd0-72f1d6d2b014)
