### ISSUE TITLE
Support for Twitter OAuth2 or State Parameter in OAuth

### ISSUE THREAD

**Issue by prabhuomkar** [markbates/goth#440]
- Is there a possibility we can get support for Twitter OAuth2 
- Currently my use case is to set `state` parameter and OAuth 1.1 by Twitter does not support that

If there are any workarounds available in this package - would really appreciate it!
PS: I have been using this package on production and thanks a ton to the maintainers!

**Comment by delaneyj** [comment]
I'm running into the exact same issue currently.

**Comment by prabhuomkar** [comment]
@markbates any update on this please?

**Comment by nicodemus-opon** [comment]
I saw a pr for this #460 hope this gets merged
