### ISSUE TITLE
Google: 400 invalid scope. How to add new ones?

### ISSUE THREAD

**Issue by GAZ082** [markbates/goth#445]
Hey. Trying to use the People API to get the users birth year (scope: user.birthday.read) and when put something like:

```
google.New(config.Config.GetString("auth.google.client_id"),
config.Config.GetString("auth.google.secret"),
"http://localhost:5000/auth/google/callback", "email", "profile", "user.birthday.read"),
)
```

Im getting an error:

```
Error 400: invalid_scope
Some requested scopes were invalid. {valid=[https://www.googleapis.com/auth/userinfo.email,
https://www.googleapis.com/auth/userinfo.profile], 
invalid=[user.birthday.read]}
```
Wonder how can I new scopes or if there is any way to make this work.

Thanks.

**Comment by GAZ082** [comment]
Anyone?

**Comment by bentranter** [comment]
@GAZ082 From the error message, it looks like the `user.birthday.read` scope is invalid. Looking at [Google's docs](https://developers.google.com/people/v1/how-tos/authorizing#profile-scopes), it appears the correct scope is the string `"https://www.googleapis.com/auth/user.birthday.read"`. I tried this locally and it worked for me, so I'm going to close this. Feel free to re-open if you continue to experience this issue.
