### ISSUE TITLE
 can't keep a user session alive

### ISSUE THREAD

**Issue by nicoxblues** [markbates/goth#468]
in this line  https://github.com/markbates/goth/blob/b4c79e79185af6f2789b53bc9baafc299384d8e6/gothic/gothic.go#L180 
  
`defer logout `
cleans up the session which prevents me from keeping the user session

**Comment by nicoxblues** [comment]
ok. 
i think this is because the user session should be handled by the web application itself and not by a library

**Comment by techknowlogick** [comment]
Yup, that's exactly it.
