### ISSUE TITLE
Support for refresh tokens

### ISSUE THREAD

**Issue by bryanl** [markbates/goth#47]
Generated access tokens most likely have an expiration date. Would it be acceptable to add support for refresh tokens and their expiration date along with a flow to refresh them?

**Comment by markbates** [comment]
Totally. I would love that.

**Comment by markbates** [comment]
Bryan, if you want commit access, I'm happy to give it to you. I trust you.

**Comment by Pym** [comment]
I would love that too! @bryanl have you had time to look into this?

**Comment by bryanl** [comment]
I put some thought in to it, but never finished. I will put in some hours over the weekend.

**Comment by rakesh-eltropy** [comment]
I would love that too! @bryanl have you had time to look into this? Not supporting refresh token is the only reason, not to use this beautiful library.

**Comment by bryanl** [comment]
@rakesh-eltropy the project I'm working on needs them, but I'm not quite there yet. I started working on it, but haven't completed it yet.

**Comment by rakesh-eltropy** [comment]
@bryanl I need it urgently. Would you mind sharing when are you expecting it to finish or I can help you ?

**Comment by rakesh-eltropy** [comment]
Just to update everybody, I have added support of refresh token and submitted the PR. Please test and let me know your feedback once its merged in the master.

**Comment by bryanl** [comment]
PR is at https://github.com/markbates/goth/pull/68 (for search engine posterity)

**Comment by rakesh-eltropy** [comment]
Mark, can you please close this issue.
