### ISSUE TITLE
Support for non-global set of providers

### ISSUE THREAD

**Issue by mitar** [markbates/goth#528]
In my case, the app can listen on multiple domains. For each domain I need a different set of callbacks for providers. It looks to me like that this is currently not possible? The set of providers is global and have a fixed set of callback URLs each? Could there be an option to have a local instance of providers? That would also be useful for testing.

**Comment by techknowlogick** [comment]
I have some good news, this is already possible :) You can have multiple providers (of the same type even) have different callback URLs (with different domains)

For example:
```
a := gitea.New(...., callbackURL1)
a.SetName("url1")
b := gitea.New(....,callbackURL2)
b.SetName("url2")
```

**Comment by mitar** [comment]
Interesting. What is then [Providers](https://pkg.go.dev/github.com/markbates/goth#Providers) used for?

**Comment by techknowlogick** [comment]
They are still technically "global" providers, but the map key is updated when you change "setName" (or at least it should be). This is how we achieve what you are wishing to do in Gitea, where we can have multiple of the same provider but with various different config (eg. log into Github, GHE, and GHE Cloud all using different instantiations of the same provider).

**Comment by mitar** [comment]
Thanks!
