### ISSUE TITLE
Extract encoded cookie when begining auth

### ISSUE THREAD

**Issue by Snorlock** [markbates/goth#55]
Hi I have a case where in developing a authorization service using different providers.
My case is that there shall be multiple frontendhosts calling towards my api for authorization through f.ex facebook. So I need to be able to know the URL that called on BeginAuth, and have access to that when the callback is fired. I cant have any form for state in my app since there might be multiple calling at the same time.

So what I need is a way of identifying the requeset that is going out to facebook, for then identifying the callback that belongs to that request. I will store the url in between the two calls.

The only way I have figured how this will work is to use the encoded cookie that is beeing sent to facebook, and returned on the callback. But unfortunately I dont have access to the cookie.

Hence this pullrequest: https://github.com/gorilla/sessions/pull/62

**Comment by Snorlock** [comment]
@markbates any suggestions? Iv tried to discuss it with the owner of sessions, https://github.com/gorilla/sessions/pull/62, but we dont get to an agreement.

**Comment by tylerb** [comment]
You should be able to handle this by simply sending some data through the `state` param that goes to the provider and comes back to you. Put whatever you need to in there to identify the original request.

**Comment by bentranter** [comment]
@Snorlock I read through your conversation with Matt in the linked issue, and I'm kind of confused about what you're trying to do. Why do you want to use JSON web tokens for authentication if you're already using Goth? Goth already handles the authentication process for you.

I'm also pretty confused about the purpose of your JavaScript code. Why do you want to open a new window to perform the authentication? You mentioned,

> Its a expeirment to hid all oauth details from the third party client app and just exchange JWT tokens after an authorization.

What do you mean by "hide all the oauth details" from the third party? Goth already does this. Do you mean hide all the Oauth details from the user? If so, I don't think that's possible - the user has to go through the Oauth dialog at least once to authenticate your service.

I went over the diagram in the Google doc you wrote, and tried my best to go through your code, and I'm still unsure about what is it you're really trying to. I'd love to help you, but I'm having a really hard time understanding the purpose of what you're trying to do. Is your goal to authenticate with JSON web tokens specifically? Or just to perform authentication in general?

**Comment by Snorlock** [comment]
@tylerb is it right to have to override the method? Or how do you set the state by yourself?

**Comment by Snorlock** [comment]
@bentranter I'm experimenting with authentication and wanted to try out JWT but wanted to have facebook/twitter/google auth in the back. And found goth to be quite simple to be able to auth the user and have some info about the user. I felt that JWT tokens was very easy to work with but I wanted to have a form of simple auth for the user. But I know I could have used the token returned from OAUTH.

Im creating an api and I want some kind of auth on the API. But a to be able to auth with goth as facebook/twitter/google and so I need some frontend to be able to view the provider auth.

Its just like how facebook does it with a modal view popping up on their javascript library.

**Comment by tylerb** [comment]
```go
v:=req.URL.Query()
v.Set("state","my state is great")
req.URL.RawQuery = v.Encode()
```

So you create your own BeginAuth function, mutate the incoming request query values, then call the BeginAuth in goth to send it through the oauth process on the provider.

**Comment by Snorlock** [comment]
I rather replaced the setstate method and set a header on the request
```
gothic.SetState = func(req *http.Request) string {
    _ = "breakpoint"
    state := r.Header.Get("state")
	  return state
}
url := r.URL.Query().Get("url")
uuid := uuid.New();

r.Header.Set("state", fmt.Sprintf("%s!%s", url, uuid))
gothic.BeginAuthHandler(w, r)

```

**Comment by rakesh-eltropy** [comment]
@Snorlock Can you please close this.
