### ISSUE TITLE
microsoftonline appears broken

### ISSUE THREAD

**Issue by jamesbalcombe83** [markbates/goth#559]
The microsoftonline provider appears to be broken. I tried to set this up using Entra in the Azure developer console, but when attempting login after setting up an app I call callback error like this

`
error: oauth2: "invalid_request" "AADSTS900144: The request body must contain the following parameter: 'code'. Trace ID: ba5c11d9-2dd8-4b1f-94ac-657adc0f6900 Correlation ID: 9ed45c68-72b0-431f-a4b6-ce9c1ba9088c Timestamp: 2024-05-22 05:26:09Z" "https://login.microsoftonline.com/error?code=900144" 
`

I followed the example in this repo, and provided all the relevant ids and secrets.

**Comment by tboerger** [comment]
If you try to set up EntraID, ex Azure AD, you got to use azureadv2 provider and not the deprecated microsoftonline integration.

**Comment by jamesbalcombe83** [comment]
> If you try to set up EntraID, ex Azure AD, you got to use azureadv2 provider and not the deprecated microsoftonline integration.

Oh this makes a lot of sense, I didn't even think to look for Azure in the provider list. The `microsoftonline` provider should probably be removed, since I assume there is no longer any way to use it at all?

**Comment by jamesbalcombe83** [comment]
I tried azureadv2 and got the same error
`error: oauth2: "invalid_request" "AADSTS900144: The request body must contain the following parameter: 'code'. Trace ID: 91e134fb-422b-4ad0-aba2-e43d379d2a01 Correlation ID: 0adc07e8-6566-4a94-ac9b-d94b0687b969 Timestamp: 2024-05-30 23:36:30Z" "https://login.microsoftonline.com/error?code=900144"`
