### ISSUE TITLE
The default example is lacking/returns errors

### ISSUE THREAD

**Issue by Rivalo** [markbates/goth#56]
When running the example I get the following error:
```goth/gothic: no SESSION_SECRET environment variable is set. The default cookie store is not available and any calls will fail. Ignore this warning if you are using a different store.```

Which gets returned by the following lines:
```go
// print our state string to the console. Ideally, you should verify
// that it's the same string as the one you set in `setState`
fmt.Println("State: ", gothic.GetState(req)) 
```

The example doesn't set it, why?

The Error also says something about a default cookie store not being available, while the documentation tells:
`Store can/should be set by applications using gothic. The default is a cookie store.`
Why isn't that default cookie store available? Also, if the documentation says that the application should set the store, why doesn't the example do this?

**Comment by markbates** [comment]
The behavior was changed recently and the example code was obviously overlooked. Please feel free and submit a PR with a fix for the example code. We'd love to have it. Thanks.
