### ISSUE TITLE
Question on how to use the package

### ISSUE THREAD

**Issue by allochi** [markbates/goth#58]
Hi,

I'm sorry, I have really tried to dig into the code, the tests and the example to find out how to do this, but I'm running late with my project and I appreciate any directions.

So far I'm able to configure the `gplus` provider, retrieve the correct account information, and I do get `_gothic_session` in my cookies using the following:

```go
goth.UseProviders(
    gplus.New(os.Getenv("GPLUS_KEY"), os.Getenv("GPLUS_SECRET"), "http://localhost:3000/auth/gplus/callback"),
)

gothic.GetProviderName = func(req *http.Request) (string, error) { 
    return "gplus", nil
}

router.GET("/auth/gplus", func(c *gin.Context) {
    gothic.BeginAuthHandler(c.Writer, c.Request)
})

router.GET("/auth/gplus/callback", func(c *gin.Context) {
    user, err := gothic.CompleteUserAuth(c.Writer, c.Request)
    if err != nil {
        fmt.Fprintln(c.Writer, err)
        return
    }
    c.JSON(http.StatusOK, user)
})
```

Now comes the funny part, what's next :D? What am I checking in the middleware to confirm that the user is logged in (and out when the session expires), I tried everything, do I keep calling `gothic.CompleteUserAuth`, because when I do I get:

```
oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_request",
  "error_description" : "Missing required parameter: code"
}
```

Could someone please provide a snippet of an authentication middleware?

Thanks!

**Comment by markbates** [comment]
Typically in an app when you get the callback from a provider you would store the user in your database for look up later. Then you would probably drop a session cookie with some sort of pointer to that user for lookup later in a piece of middleware.

Since those steps are 100% unique to your application there is no "default" way to do it, which is why `goth` and `gothic` don't provide one. Once you get the callback from the provider it's up to you to do what is necessary for your application.

Hope that answers your question.

**Comment by allochi** [comment]
@markbates Thanks! That's exactly what I was looking for, I wasn't sure if `goth` was suppose to handle the session since it create `_gothic_session`, and I though I was missing something.

Thanks for your replay, and thank for `goth`, it's amazing.

**Comment by sungwoncho** [comment]
@markbates I was wondering the similar thing because goth set `_gothic_session` cookie. What is the purpose of `_gothic_session` cookie?

**Comment by markbates** [comment]
It holds on to information such a as which provider you are using so when you come back from the authenticating with that provider it can finish the process. Without it there would be no way of knowing that you clicked on Facebook, for example.
