### ISSUE TITLE
[question] Doesn't it allow several callbacks?

### ISSUE THREAD

**Issue by im7mortal** [markbates/goth#76]
Hi! 
In _passport.js_ you can use one **callbackURL** for signup and another for logging. Also separate callback is  necessary for deactivating account. It's comfy. 
I noticed that _func New(clientKey, secret, callbackURL string, scopes ...string) *Provider {}_ allow only one callback. I got that function from _facebook provider_. I noticed it standard function for all providers.
I am doing it via _gothic_ also 
Is there are some approach for my need?

**Comment by im7mortal** [comment]
I noticed that only facebook allow several callbacksURL. It's pretty comfy. But majority providers keep only one callbackURL.
I think It possible to do some function which will set custom callback.
Is it redundant? If only for providers who allow it? For example for facebook?

**Comment by willemvd** [comment]
The callbackURL is used to tell the provider, on the initial login request, where to redirect to when the login flow is successfully finished. 
Facebook indeed allows you to specify multiple urls that are accepted for the value you send it, but as the call initiator you are required to tell it which one to use.

What is the case that you would like to send facebook to use another return url?

**Comment by im7mortal** [comment]
@willemvd I don't remember exactly. 
<https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow>
Last paragraph about _Detecting When People Uninstall Apps_ **Deauthorize Callback URL**
I don't remember why I decided that it should be in provider.
Maybe I was wrong.

**Comment by bentranter** [comment]
Closing this due to age, feel free to re-open if it's still an issue.
