### ISSUE TITLE
Not working for Twitter

### ISSUE THREAD

**Issue by motyar** [markbates/goth#85]
I am getting this error with Twitter, please help

`getBody: httpExecute: HTTP response is not 200/OK as expected. Actual response: 
    Response Status: '401 Authorization Required'
    Response Code: 401
    Response Body: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
    Request Headers: [key: Authorization, val: OAuth oauth_callback="http%3A%2F%2F162.243.216.116%3A3000%2Fauth%2Ftwitter%2Fcallback",oauth_consumer_key="bu7KHEjK7UTfNReTcG4gK",oauth_nonce="1527203789697",oauth_signature="Y0zXln26LPHveIjbs%3D",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1465900095",oauth_version="1.0"]`

Here is the code I am using: https://gist.github.com/motyar/dd1a441ed7214439afcb388b6c26b567

**Comment by icyswift** [comment]
hiya motyar,

your oauth consumer key in the header does not match the consumer key in the code
header: bu7KHEjK7UTfNReTcG4gK
code    : bu7D17UKHEjK7UTfNReTcG4gK

Does the consumer key in your code match the one from the twitter developer dashboard :question:
