### ISSUE TITLE
Excellent library

### ISSUE THREAD

**Issue by kataras** [markbates/goth#86]
Nice job to contributors, I just convert it to work with the [Iris web framework](https://github.com/kataras/iris) !

You could write a new section on README with the packages uses your library (Iris is first on 'All Languages' Github Trends and Go Trends) this method will give you traffic.

**Comment by zmb3** [comment]
I see you copied the gothic package to [iris-contrib/gothic](https://github.com/iris-contrib/gothic), but didn't retain the original license or copyright - which technically violates goth's MIT license:

> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.

You really should attribute the work to its original author(s).

**Comment by markbates** [comment]
Yeah, that's not cool dude.

**Comment by kataras** [comment]
I did on the package name lol..  I'm adding the README also, cool lawl

**Comment by kataras** [comment]
@markbates  Done, although I had did that on package-level because it was only one file.

[better support ](https://github.com/kataras/iris/commit/4a446ac1e227b34263123a41bece6f10292e32f8)by iris now ( this is why I late to answer)

**Comment by kataras** [comment]
@zmb3 I am, maybe you don't watching my work... np :)

**Comment by kataras** [comment]
@markbates  Done, although I had did that on package-level because it was only one file.

@zmb3 [I](https://github.com/kataras/iris/blob/master/THIRDPARTY.md) am, [here](https://github.com/iris-contrib/gothic/blob/master/gothic.go#L2) it [is](https://github.com/iris-contrib/gothic/#license) ... 

[better support ](https://github.com/kataras/iris/commit/4a446ac1e227b34263123a41bece6f10292e32f8)by iris now ( this is why I late to answer)

**Comment by kataras** [comment]
@markbates  Done, although I had did that on package-level because it was only one file.

@zmb3 [I](https://github.com/kataras/iris/blob/master/THIRDPARTY.md) am, [here](https://github.com/iris-contrib/gothic/blob/master/gothic.go#L2) it [is](https://github.com/iris-contrib/gothic/#license) ... 

[better support ](https://github.com/kataras/iris/commit/4a446ac1e227b34263123a41bece6f10292e32f8)by iris now ( this is why I late to answer), yours turn now :)

**Comment by kataras** [comment]
@markbates  [Done](https://github.com/iris-contrib/gothic/#license), although I had did that on [package-level](https://github.com/iris-contrib/gothic/blob/master/gothic.go#L2) because it was only one file, added to the iris/thirdparty.md also.

@zmb3 [I](https://github.com/kataras/iris/blob/master/THIRDPARTY.md) am, [here](https://github.com/iris-contrib/gothic/blob/master/gothic.go#L2) it [is](https://github.com/iris-contrib/gothic/#license) ... 

[better support ](https://github.com/kataras/iris/commit/4a446ac1e227b34263123a41bece6f10292e32f8)by iris now ( this is why I late to answer), yours turn now :)
