### ISSUE TITLE
Would we have a proper support for generic SAML?

### ISSUE THREAD

**Issue by wanghong230** [markbates/goth#92]
SAML would be super helpful for enterprise area.

**Comment by markbates** [comment]
If you want to write a SAML document, I wouldn't be opposed to it. With that said, all of the providers are either OAuth or OAuth 2.0, so I'm not sure what a SAML document would provide.

**Comment by bentranter** [comment]
Closing this due to age, feel free to re-open if it's still an issue. Personally I don't think Goth should support SAML, considering there are other dedicated Go libraries for SAML, but if folks feel differently, we can consider it.
