### ISSUE TITLE
how to provide appsecret_proof argumet to fb calls ?

### ISSUE THREAD

**Issue by thomasmodeneis** [markbates/goth#96]
Hi,

I could not find this on the web, 

After enabling Require app secret for server API calls I'm running into error`API calls from the server require an appsecret_proof argument`. Is there a way to set appsecret_proof argument ?

Thanks.

**Comment by willemvd** [comment]
Updated the facebook provider to always set this appsecret_proof when doing the api call.
Works with both the facebook setting "Require App Secret  Only allow calls from a server and require app secret or app secret proof for all API calls." enabled and disabled
